version: "3"

volumes:
  mysql:
    driver: local
  phpmyadmin:
    driver: local

services:
  ### MySQL ################################################
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starwars
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    ports:
      - "3306:3306"

  ### phpMyAdmin ###########################################
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
